"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Bell, Eye, Heart, Plus, X } from "lucide-react";
import type { SocialAlert } from "@/lib/social-alert";
import { socialAlertLabel, socialAlertPrimaryAction } from "@/lib/social-alert";
export function SocialAlertsTray() {
  const [alerts, setAlerts] = useState<SocialAlert[]>([]); const [open, setOpen] = useState(false);
  useEffect(() => { let active = true; const load = async () => { try { const response = await fetch("/api/account/alerts?limit=20", { credentials: "same-origin" }); if (!response.ok) return; const data = await response.json() as { alerts?: SocialAlert[] }; if (active) setAlerts(data.alerts?.filter((alert) => !alert.read) ?? []); } catch {} }; void load(); const timer = window.setInterval(load, 15_000); return () => { active = false; window.clearInterval(timer); }; }, []);
  async function dismiss(id: string) { setAlerts((current) => current.filter((alert) => alert.id !== id)); await fetch("/api/account/alerts", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }).catch(() => undefined); }
  const visible = open ? alerts : alerts.slice(0, 3); if (!visible.length) return null;
  return <section aria-label="Creator alerts" className="fixed right-3 top-[calc(4.25rem+var(--live-ribbon-h,0px))] z-[96] flex w-[min(24rem,calc(100vw-1.5rem))] flex-col gap-2">{visible.map((alert) => <article key={alert.id} className="group overflow-hidden rounded-2xl border border-white/15 bg-[#151519]/95 text-white shadow-2xl backdrop-blur-xl"><div className="flex gap-3 p-3">{alert.artworkUrl ? <img src={alert.artworkUrl} alt="" className={`h-16 w-24 shrink-0 rounded-lg object-cover ${alert.orientation === "portrait" ? "w-12" : ""}`} /> : <span className="grid size-10 shrink-0 place-items-center rounded-full bg-[color:var(--core)]/20 text-[color:var(--core)]"><Bell className="size-4" /></span>}<Link href={alert.href as never} onClick={() => void dismiss(alert.id)} className="min-w-0 flex-1"><span className={`text-[10px] font-bold uppercase tracking-wider ${alert.contentType === "live" ? "text-red-400" : "text-white/50"}`}>{socialAlertLabel(alert)}</span><strong className="mt-0.5 line-clamp-2 block text-sm leading-snug">{alert.title}</strong><span className="mt-1 line-clamp-1 block text-[11px] text-white/55">{alert.body}</span></Link><button type="button" onClick={() => void dismiss(alert.id)} className="grid size-8 shrink-0 place-items-center rounded-lg text-white/35 transition hover:bg-white/10 hover:text-white" aria-label="Dismiss alert"><X className="size-3.5" /></button></div><div className="flex gap-2 border-t border-white/10 px-3 py-2"><Link href={alert.href as never} onClick={() => void dismiss(alert.id)} className="inline-flex min-h-8 items-center rounded-lg bg-white px-3 text-xs font-semibold text-black transition hover:bg-white/85">{socialAlertPrimaryAction(alert)}</Link>{alert.contentType === "live" ? <button type="button" onClick={() => void dismiss(alert.id)} className="inline-flex min-h-8 items-center gap-1 rounded-lg px-2 text-xs font-semibold text-white/70 transition hover:bg-white/10 hover:text-white"><Plus className="size-3.5" />Add tile</button> : <button type="button" onClick={() => void dismiss(alert.id)} className="inline-flex min-h-8 items-center gap-1 rounded-lg px-2 text-xs font-semibold text-white/70 transition hover:bg-white/10 hover:text-white"><Heart className="size-3.5" />Save</button>}<button type="button" onClick={() => void dismiss(alert.id)} className="ml-auto inline-flex min-h-8 items-center gap-1 rounded-lg px-2 text-xs font-semibold text-white/55 transition hover:bg-white/10 hover:text-white"><Eye className="size-3.5" />{alert.contentType === "live" ? "Keep watching" : "Later"}</button></div></article>)}{alerts.length > 3 ? <button type="button" onClick={() => setOpen(!open)} className="self-end rounded-full bg-[#151519]/95 px-3 py-1.5 text-xs font-semibold text-white shadow-lg ring-1 ring-white/15">{open ? "Close inbox" : `${alerts.length - 3} more alerts`}</button> : null}</section>;
}
