"use client";
import { useEffect, useState } from "react";
import { Bell01, Mail01, NotificationBox, VideoRecorder } from "@untitledui/icons";
import { Toggle } from "@/components/base/toggle/toggle";
import type { SocialContentType } from "@/lib/social-alert";
const types: Array<{ key: SocialContentType; label: string }> = [{ key: "live", label: "Live" }, { key: "video", label: "Videos" }, { key: "short", label: "Shorts" }, { key: "photo", label: "Photos" }, { key: "post", label: "Posts" }];
type Settings = { enabled: boolean; inAppEnabled: boolean; pushEnabled: boolean; emailEnabled: boolean; rules: Array<{ memberSlug: string; contentType: SocialContentType; enabled: boolean }> };
const defaults: Settings = { enabled: true, inAppEnabled: true, pushEnabled: false, emailEnabled: false, rules: [] };
function urlBase64ToUint8Array(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const base64 = (value + padding).replace(/-/g, "+").replace(/_/g, "/"); return Uint8Array.from(atob(base64), (character) => character.charCodeAt(0)); }
export function SocialNotificationSettings({ members }: { members: Array<{ slug: string; stageName: string }> }) {
  const [settings, setSettings] = useState<Settings>(defaults); const [ready, setReady] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/account/social-notifications", { credentials: "same-origin" }).then((response) => response.ok ? response.json() : null).then((data) => { if (data?.settings) setSettings(data.settings); setReady(true); }).catch(() => { setMessage("Couldn’t load alert settings."); setReady(true); }); }, []);
  async function save(next: Settings) { setSettings(next); setSaving(true); setMessage(""); try { const response = await fetch("/api/account/social-notifications", { method: "PUT", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify(next) }); if (!response.ok) throw new Error(); setMessage("Saved"); } catch { setSettings(settings); setMessage("Couldn’t save that change."); } finally { setSaving(false); } }
  function ruleEnabled(memberSlug: string, contentType: SocialContentType) { return settings.rules.find((rule) => rule.memberSlug === memberSlug && rule.contentType === contentType)?.enabled ?? true; }
  function setRule(memberSlug: string, contentType: SocialContentType, enabled: boolean) { const rules = settings.rules.filter((rule) => !(rule.memberSlug === memberSlug && rule.contentType === contentType)); void save({ ...settings, rules: [...rules, { memberSlug, contentType, enabled }] }); }
  async function setPush(enabled: boolean) { if (!enabled) { void save({ ...settings, pushEnabled: false }); return; } try { const availability = await fetch("/api/account/push-subscriptions").then((response) => response.json()); if (!availability.publicKey || !("serviceWorker" in navigator) || !("PushManager" in window)) throw new Error("unsupported"); const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("denied"); const registration = await navigator.serviceWorker.register("/core-push-sw.js"); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToUint8Array(availability.publicKey) }); const result = await fetch("/api/account/push-subscriptions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(subscription) }); if (!result.ok) throw new Error("save"); void save({ ...settings, pushEnabled: true }); } catch { setMessage("Browser alerts need permission and configured push delivery."); } }
  if (!ready) return <div className="h-64 animate-pulse rounded-2xl bg-secondary" />;
  return <section className="overflow-hidden rounded-2xl bg-secondary shadow-xl ring-1 ring-inset ring-secondary"><div className="flex flex-wrap items-start justify-between gap-4 p-5 sm:p-6"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-primary text-brand-secondary"><Bell01 className="size-5" /></span><div><h2 className="text-lg font-semibold text-primary">Creator alerts</h2><p className="mt-1 max-w-xl text-sm text-tertiary">In-app alerts are on by default. Browser alerts and email only turn on after you opt in.</p></div></div><span className="text-xs font-semibold text-tertiary">{saving ? "Saving…" : message}</span></div><div className="grid border-y border-secondary sm:grid-cols-2 xl:grid-cols-4"><SettingToggle icon={VideoRecorder} label="All alerts" selected={settings.enabled} onChange={(enabled) => void save({ ...settings, enabled })}/><SettingToggle icon={Bell01} label="In-app" selected={settings.inAppEnabled} onChange={(inAppEnabled) => void save({ ...settings, inAppEnabled })}/><SettingToggle icon={NotificationBox} label="Browser push" selected={settings.pushEnabled} onChange={setPush}/><SettingToggle icon={Mail01} label="Email" selected={settings.emailEnabled} onChange={(emailEnabled) => void save({ ...settings, emailEnabled })}/></div><div className="overflow-x-auto"><div className="min-w-[42rem]"><div className="grid grid-cols-[12rem_repeat(5,1fr)] border-b border-secondary px-5 py-3 text-xs font-semibold text-tertiary"><span>Creator</span>{types.map((type) => <span key={type.key} className="text-center">{type.label}</span>)}</div>{members.map((member) => <div key={member.slug} className="grid grid-cols-[12rem_repeat(5,1fr)] items-center border-b border-secondary px-5 py-3 last:border-0"><span className="text-sm font-semibold text-primary">{member.stageName}</span>{types.map((type) => <span key={type.key} className="flex justify-center"><Toggle size="sm" isSelected={ruleEnabled(member.slug, type.key)} onChange={(enabled) => setRule(member.slug, type.key, enabled)} aria-label={`${member.stageName} ${type.label} alerts`}/></span>)}</div>)}</div></div></section>;
}
function SettingToggle({ icon: Icon, label, selected, onChange }: { icon: typeof Bell01; label: string; selected: boolean; onChange: (enabled: boolean) => void }) { return <div className="flex items-center justify-between gap-3 border-b border-secondary p-4 sm:border-b-0 sm:border-r last:border-0"><span className="flex items-center gap-2 text-sm font-semibold text-primary"><Icon className="size-4 text-tertiary" />{label}</span><Toggle size="sm" isSelected={selected} onChange={onChange} aria-label={label}/></div>; }
