import { NextResponse } from "next/server";
import { getCurrentFanUserId } from "@/lib/fan-auth";
import { removePushSubscription, upsertPushSubscription } from "@/lib/social-events";
import { getSocialNotificationDeliveryReadiness } from "@/lib/social-delivery";
import { EntitlementDeniedError, requireAccountEntitlement } from "@/lib/subscriptions/entitlements";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
function privateJson(body: unknown, init?: ResponseInit) { const response = NextResponse.json(body, init); response.headers.set("Cache-Control", "private, no-store"); response.headers.set("Vary", "Cookie"); return response; }
export async function GET() { const userId = await getCurrentFanUserId(); if (!userId) return privateJson({ error: "unauthorized" }, { status: 401 }); const readiness = getSocialNotificationDeliveryReadiness(); return privateJson({ publicKey: process.env.VAPID_PUBLIC_KEY ?? null, enabled: readiness.push.ready, readiness: readiness.push }); }
export async function POST(request: Request) { const userId = await getCurrentFanUserId(); if (!userId) return privateJson({ error: "unauthorized" }, { status: 401 }); try { await requireAccountEntitlement({ userId, requestHostname: new URL(request.url).hostname, featureId: "notifications.advanced" }); } catch (error) { if (error instanceof EntitlementDeniedError) return privateJson({ error: error.code, featureId: error.featureId, requiredPlanId: error.requiredPlanId, upgradeHref: `/upgrade?feature=${encodeURIComponent(error.featureId)}` }, { status: 403 }); throw error; } const readiness = getSocialNotificationDeliveryReadiness(); if (!readiness.push.ready) return privateJson({ error: "push_not_ready", readiness: readiness.push }, { status: 503 }); const body = await request.json().catch(() => null); const keys = body?.keys; if (!body || typeof body.endpoint !== "string" || !keys || typeof keys.p256dh !== "string" || typeof keys.auth !== "string") return privateJson({ error: "invalid_payload" }, { status: 400 }); try { await upsertPushSubscription(userId, { endpoint: body.endpoint, p256dh: keys.p256dh, auth: keys.auth, expirationTime: body.expirationTime, userAgent: request.headers.get("user-agent") }); return privateJson({ ok: true }); } catch { return privateJson({ error: "invalid_subscription" }, { status: 400 }); } }
export async function DELETE(request: Request) { const userId = await getCurrentFanUserId(); if (!userId) return privateJson({ error: "unauthorized" }, { status: 401 }); const body = await request.json().catch(() => null); if (!body || typeof body.endpoint !== "string") return privateJson({ error: "invalid_payload" }, { status: 400 }); await removePushSubscription(userId, body.endpoint); return privateJson({ ok: true }); }
